# Generated by Django 4.2 on 2023-07-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.CharField(blank=True, db_comment='habiltado, deshabiliado', default='habilitado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='estado',
            field=models.CharField(blank=True, db_comment='habiltado, deshabiliado', default='habilitado', max_length=20, null=True),
        ),
    ]
